#!/bin/sh
OCTAVE=$(which octave)
if [ -z $OCTAVE ]
then
	echo "Error: octave binary not found"
	exit 1
fi
if [ $# -ne 1 ]
then
	echo "Usage: dsr <filename>"
	exit 2
fi
echo "warning('off');DSR('$1');" | $OCTAVE --quiet --no-history --no-window-system
